### ISSUE TITLE
database_driver_options

### ISSUE THREAD

**Issue by chaitralideshmukh** [oroinc/orocommerce#60]
[Symfony\Component\DependencyInjection\Exception\ParameterNotFoundException]  
  You have requested a non-existent parameter "database_driver_options".

getting this error while running command :php app/console oro:install --env=prod

**Comment by vsoroka** [comment]
it is a new parameter, please run composer install

**Comment by chaitralideshmukh** [comment]
yes tried to run this command also
 composer install --prefer-dist --no-dev 
then getting this error: 
[Composer\Downloader\TransportException]                                                                 
  The "https://packagist.orocrm.com/packages.json" file could not be downloaded: SSL: Handshake timed out  
  Failed to enable crypto                                                                                  
  failed to open stream: operation failed

**Comment by yurio** [comment]
Hello, @chaitralideshmukh.
The problem was fixed. Please try to run composer install one more time.

**Comment by chaitralideshmukh** [comment]
after command
composer install --prefer-dist --no-dev
 i run this command " php app/console oro:install --env=prod" 
still getting error 
  [Symfony\Component\DependencyInjection\Exception\ParameterNotFoundException]  
  You have requested a non-existent parameter "database_driver_options".

**Comment by zainengineer** [comment]
in your parameters add 
`database_driver_options: []` 
Its probably caused by this commit
https://github.com/oroinc/platform/commit/e481b1b4a39c32aefa1ef778e182d066e07f07a4

**Comment by dxops** [comment]
Hi, the error means that your application is not up to date, please update app when running composer update to update packages
